name: Build and Release

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
          
      - name: Set env variable
        run: |
          echo "BUILD_TIME=$(date +'%Y%m%d')" >> $GITHUB_ENV
          echo "COMMIT_SHA_SHORT=$(git rev-parse --short ${{ github.sha }})" >> $GITHUB_ENV
          echo ${{env.BUILD_TIME}}
          echo ${{env.COMMIT_SHA_SHORT}}
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          
      - name: Install dependencies
        run: npm ci
        
      - name: Build project
        run: |
          npm run build
          du -h dist/
        
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: dist/  # 假设构建结果在dist目录

  deploy:
    needs: build
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    permissions:
      pages: write
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
        
